apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: qasim313/nodejs-app:latest  # Corrected image name
          imagePullPolicy: Always  # Ensure latest image is pulled
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
  namespace: test
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

